import sqlite3
from collections import Counter

DB = r"..\data\basketball.db"
conn = sqlite3.connect(DB)

CBBD_TO_TORVIK = {
    'A&M-Corpus Christi': 'Texas A&M Corpus Chris',
    'ALR': 'Little Rock',
    'AR-Pine Bluff': 'Arkansas Pine Bluff',
    'ASU': 'Arizona St.',
    'Abil Chr': 'Abilene Christian',
    'Abil Christian': 'Abilene Christian',
    'Abil Cristian': 'Abilene Christian',
    'Abil. Christian': 'Abilene Christian',
    'Abilene Chr.': 'Abilene Christian',
    'Abilene Christian Univ': 'Abilene Christian',
    'Abilene Christian University': 'Abilene Christian',
    'Alabama Birmingham': 'Alabama-Birmingham',
    'Alabama St': 'Alabama St.',
    'Alabama State': 'Alabama St.',
    'American Univ': 'American',
    'App St': 'Appalachian St.',
    'App St.': 'Appalachian St.',
    'App. St.': 'Appalachian St.',
    'Appalachian St': 'Appalachian St.',
    'Appalachian State': 'Appalachian St.',
    'Arizona St': 'Arizona St.',
    'Arizona State': 'Arizona St.',
    'Ark Pine Bluff': 'Arkansas Pine Bluff',
    'Ark.-Pine Bluff': 'Arkansas Pine Bluff',
    'Arkansas Little Rock': 'Little Rock',
    'Arkansas-LR': 'Little Rock',
    'Arkansas-Pine Bluff': 'Arkansas Pine Bluff',
    'BSU': 'Boise St.',
    'Boise St': 'Boise St.',
    'Boise State': 'Boise St.',
    'C Michigan': 'Central Michigan',
    'C. Michigan': 'Central Michigan',
    'CMU': 'Central Michigan',
    'CSU Bakersfield': 'Cal St. Bakersfield',
    'CSU-Bakersfield': 'Cal St. Bakersfield',
    'Cal State Bakersfield': 'Cal St. Bakersfield',
    'CalBaptist': 'Cal Baptist',
    'California Baptist': 'Cal Baptist',
    'Cent Conn St': 'Central Connecticut',
    'Cent Michigan': 'Central Michigan',
    'Cent. Conn. St.': 'Central Connecticut',
    'Central Mich': 'Central Michigan',
    'Central Mich.': 'Central Michigan',
    'Chicago St': 'Chicago St.',
    'Chicago State': 'Chicago St.',
    'Cleveland St': 'Cleveland St.',
    'Cleveland State': 'Cleveland St.',
    'Coast Carolina': 'Coastal Carolina',
    'Coppin St': 'Coppin St.',
    'Coppin State': 'Coppin St.',
    'Delaware St': 'Delaware St.',
    'Delaware State': 'Delaware St.',
    'E Illinois': 'Eastern Ilinois',
    'E Michigan': 'Eastern Michigan',
    'E. Illinois': 'Eastern Ilinois',
    'E. Michigan': 'Eastern Michigan',
    'ETSU': 'East Tennessee St.',
    'East Tennesse State': 'East Tennessee St.',
    'East Texas A&M': 'Texas A&M-Commerce',
    'F Dickinson': 'Farleigh Dickinson',
    'FAU': 'Florida Atlantic',
    'FGCU': 'Florida Gulf Coast',
    'FL Atlantic': 'Florida Atlantic',
    'Florida Intl': 'Florida International',
    'Fresno St': 'Fresno St.',
    'Fresno State': 'Fresno St.',
    'Houston Chr': 'Houston Christian',
    'IU Indy': 'IU Indianapolis',
    'IUPUI': 'IU Indianapolis',
    'Idaho St': 'Idaho St.',
    'Idaho State': 'Idaho St.',
    'Illinois St': 'Illinois St.',
    'Illinois State': 'Illinois St.',
    'Indiana St': 'Indiana St.',
    'Indiana State': 'Indiana St.',
    'Jacksonville': 'Jacksonville St.',
    'Jacksonville St': 'Jacksonville St.',
    'Jacksonville State': 'Jacksonville St.',
    'Kennessaw St': 'Kennesaw St.',
    'Kennessaw St.': 'Kennesaw St.',
    'Kennessaw State': 'Kennesaw St.',
    'Kent': 'Kent St.',
    'Kent St': 'Kent St.',
    'Kent State': 'Kent St.',
    'LA Tech': 'Louisiana Tech',
    'LIU Brooklyn': 'LIU',
    'La Tech': 'Louisiana Tech',
    'La. Tech': 'Louisiana Tech',
    'Lamar University': 'Lamar',
    'Long Island': 'LIU',
    'Louisiana': 'Louisiana',
    'MD E Shore': 'Maryland-Eastern Shore',
    'MES': 'Maryland-Eastern Shore',
    'MS Valley St': 'Mississippi Valley State',
    'MS Valley St.': 'Mississippi Valley State',
    'MS Valley State': 'Mississippi Valley State',
    'Maryland Eastern Shore': 'Maryland-Eastern Shore',
    'McNeese': 'McNeese St.',
    'McNeese St': 'McNeese St.',
    'McNeese State': 'McNeese St.',
    'Miami': 'Miami FL',
    'Miami FL': 'Miami FL',
    'Miami FL.': 'Miami FL',
    'Miami Florida': 'Miami FL',
    'Miami Oh.': 'Miami OH',
    'Miami Ohio': 'Miami OH',
    'Miami-FL': 'Miami FL',
    'Miami-OH': 'Miami OH',
    'Michigan St': 'Michigan St.',
    'Michigan State': 'Michigan St.',
    'Miss. Valley St.': 'Mississippi Valley State',
    'Mississippi Rebels': 'Mississippi',
    'Mississippi Va.': 'Mississippi Valley State',
    'Mississippi Valley St.': 'Mississippi Valley State',
    'Morgan St': 'Morgan St.',
    'Morgan State': 'Morgan St.',
    'N Dakota St': 'North Dakota St.',
    'N. Dakota St.': 'North Dakota St.',
    'N. Dakota State': 'North Dakota St.',
    'N. Illinois': 'Northern Illinois',
    'NC Central': 'North Carolina Central',
    'NCC': 'North Carolina Central',
    'NIU': 'Northern Illinois',
    'Nicholls': 'Nicholls St.',
    'Nicholls St': 'Nicholls St.',
    'Nicholls State': 'Nicholls St.',
    'Norfolk St': 'Norfolk St.',
    'Norfolk State': 'Norfolk St.',
    'North Dakota State': 'North Dakota St.',
    'Northwestern St': 'Northwestern St.',
    'Northwestern State': 'Northwestern St.',
    'Ole Miss': 'Mississippi',
    'PV A&M': 'Prairie View',
    'Portland St': 'Portland St.',
    'Portland State': 'Portland St.',
    'Prairie View A&M': 'Prairie View',
    'Queens NC': 'Queens',
    'Rhode Isl': 'Rhode Island',
    'S Carolina St': 'South Carolina St.',
    'S Illinois': 'Southern Illinois',
    'S. Carolina St.': 'South Carolina St.',
    'SE Lousiana': 'Southeastern La.',
    'SE Missouri St': 'Southeast Missouri St.',
    'SE Missouri St.': 'Southeast Missouri St.',
    'SE Missouri State': 'Southeast Missouri St.',
    'SEMO': 'Southeast Missouri St.',
    'SF Austin': 'Stephen F. Austin',
    'SFA': 'Stephen F. Austin',
    'SIU Edwardsville': 'SIU-Edwardsville',
    'SIUE': 'SIU-Edwardsville',
    'Saint Francis': 'Saint Francis',
    'Saint Francis (PA)': 'Saint Francis',
    'Saint Francis U': 'Saint Francis',
    "Saint John's": "St. John's (NY)",
    'Sam Houston': 'Sam Houston St.',
    'Sam Houston St': 'Sam Houston St.',
    'Sam Houston State': 'Sam Houston St.',
    'So Dakota State': 'South Dakota St.',
    'So. Dakota State': 'South Dakota St.',
    'South Carolina State': 'South Carolina St.',
    'South Dakota St': 'South Dakota St.',
    'South Dakota State': 'South Dakota St.',
    'Southeast Missouri State': 'Southeast Missouri St.',
    'Southeastern LA': 'Southeastern La.',
    'Southeastern La': 'Southeastern La.',
    'Southeastern Louisiana': 'Southeastern La.',
    'Southern': 'Southern U.',
    'Southern Univ': 'Southern U.',
    'Southern University': 'Southern U.',
    "St John's": "St. John's (NY)",
    'St. Francis': 'Saint Francis',
    "St. John's": "St. John's (NY)",
    'Stephen F Austin': 'Stephen F. Austin',
    'TAM C. Christi': 'Texas A&M Corpus Chris',
    'Tarleton': 'Tarleton St.',
    'Tarleton St': 'Tarleton St.',
    'Tarleton State': 'Tarleton St.',
    'Tex. A&M-Commerce': 'Texas A&M-Commerce',
    'Texas A&M CC': 'Texas A&M Corpus Chris',
    'Texas A&M Corpus Chris': 'Texas A&M Corpus Chris',
    'Texas A&M Corpus Christi': 'Texas A&M Corpus Chris',
    'Texas A&M-CC': 'Texas A&M Corpus Chris',
    'Texas Christian': 'TCU',
    'Texas So': 'Texas Southern',
    'Texas So.': 'Texas Southern',
    'Towson (MMMT)': 'Towson',
    'Towson MMMT': 'Towson',
    'UAB': 'Alabama-Birmingham',
    'UCD': 'UC Davis',
    'UCSB': 'UC Santa Barbara',
    'UConn': 'Connecticut',
    'UIW': 'Incarnate Word',
    'UL Lafayette': 'Louisiana',
    'UMES': 'Maryland-Eastern Shore',
    'UMKC': 'Kansas City',
    'UNCG': 'UNC Greensboro',
    'UNCW': 'UNC Wilmington',
    'URI': 'Rhode Island',
    'USC': 'Southern California',
    'UTRGV': 'UT Rio Grande Valley',
    'Univ Southern California': 'Southern California',
    'Univ. of Southern California': 'Southern California',
    'Utah St': 'Utah St.',
    'Utah State': 'Utah St.',
    'W Carolina': 'Western Carolina',
    'W Illinois': 'Western Illinois',
    'W Michigan': 'Western Michigan',
    'W. Carolina': 'Western Carolina',
    'W. Illinois': 'Western Illinois',
    'W. Michigan': 'Western Michigan',
    'Western Caro.': 'Western Carolina',
    'Wichita St': 'Wichita St.',
    'Wichita State': 'Wichita St.',
    'abilchristian': 'Abilene Christian',
    'abilenechristian': 'Abilene Christian',
    'arizonast': 'Arizona St.',
    'arizonastate': 'Arizona St.',
    'calbaptist': 'Cal Baptist',
    'calstbakersfield': 'Cal St. Bakersfield',
    'centmichigan': 'Central Michigan',
    'centralmichigan': 'Central Michigan',
    'charlestonso': 'Charleston Southern',
    'charlestonsouthern': 'Charleston Southern',
    'coastalcarolina': 'Coastal Carolina',
    'coastcarolina': 'Coastal Carolina',
    'coppinstate': 'Coppin St.',
    'csubakersfield': 'Cal St. Bakersfield',
    'easternillinois': 'Eastern Ilinois',
    'eillinois': 'Eastern Ilinois',
    'illinoisst': 'Illinois St.',
    'illinoisstate': 'Illinois St.',
    'indianast': 'Indiana St.',
    'iuindy': 'IU Indianapolis',
    'jacksonvillestate': 'Jacksonville St.',
    'mcneese': 'McNeese St.',
    'mississippi': 'Mississippi',
    'mississippivalleystate': 'Mississippi Valley State',
    'norfolkstate': 'Norfolk St.',
    'olemiss': 'Mississippi',
    'rhodeisland': 'Rhode Island',
    'sfa': 'Stephen F. Austin',
    'tarletonst': 'Tarleton St.',
    'towsonmnmt': 'Towson',
    'umes': 'Maryland-Eastern Shore',
    'usc': 'Southern California',
    'utahtech': 'Utah Tech',
    'westernillinois': 'Western Illinois',
    'willinois': 'Western Illinois',
    'American University': 'American',
    'App State': 'Appalachian St.',
    'Alcorn State': 'Alcorn St.',
    'UL Monroe': 'Louisiana Monroe',
    'North Dakota': 'North Dakota',

    'Saint Joseph\'s': 'Saint Joseph\'s',
    'Saint Mary\'s (CA)': 'Saint Mary\'s',
    'Saint Peter\'s': 'Saint Peter\'s',
    'Saint Louis': 'Saint Louis',

    'Miami (OH)': 'Miami OH',
    'Miami (FL)': 'Miami FL',
    'NC State': 'North Carolina St.',
    'North Carolina State': 'North Carolina St.',

    'Louisiana-Monroe': 'Louisiana Monroe',
    'Louisiana-Lafayette': 'Louisiana',
    'Abilene-Christian': 'Abilene Christian',
    'North-Carolina': 'North Carolina',
    'Texas-Arlington': 'UT Arlington',
    'Arkansas-Little Rock': 'Little Rock',
    'North Carolina-Asheville': 'UNC Asheville',
    'North Carolina-Greensboro': 'UNC Greensboro',
    'North Carolina-Wilmington': 'UNC Wilmington',
    'North Carolina-Charlotte': 'Charlotte',
    'North Carolina-Pembroke': 'UNC Pembroke',
    'University of California': 'California',
    'UC Irvine': 'UC Irvine',
    'UC Davis': 'UC Davis',
    'UC Riverside': 'UC Riverside',
    'UC Santa Barbara': 'UC Santa Barbara',
    'UC San Diego': 'UC San Diego',

}

def norm(name):
    if not name: return name
    return CBBD_TO_TORVIK.get(str(name).strip(), str(name).strip())

games_teams = set()
for t in conn.execute("SELECT DISTINCT home_team FROM games UNION SELECT DISTINCT away_team FROM games"):
    games_teams.add(t[0])

daily_teams = set()
for t in conn.execute("SELECT DISTINCT team FROM torvik_daily"):
    daily_teams.add(t[0])

counts = Counter()
for row in conn.execute("SELECT home_team, away_team FROM games"):
    counts[row[0]] += 1
    counts[row[1]] += 1

missing = []
for t in sorted(games_teams):
    normed = norm(t)
    if normed not in daily_teams:
        missing.append((t, normed, counts.get(t, 0)))

missing.sort(key=lambda x: -x[2])
significant = [(t, n, c) for t, n, c in missing if c > 5]

print(f"Games teams: {len(games_teams)} | Daily teams: {len(daily_teams)}")
print(f"Missing after norm (>5 games): {len(significant)}")
for t, n, c in significant[:60]:
    print(f"  {t!r:40s} -> {n!r:40s} ({c} games)")

conn.close()
